### ISSUE TITLE
improve access to annotations of Document

### ISSUE THREAD

**Issue by Bhuvanesh-Verma** [ChristophAlt/pytorch-ie#111]
If annotation type is a variable then currently only way to access annotations by their name is by iterating over a loop like in [clear_predictions](https://github.com/ChristophAlt/pytorch-ie/blob/2eb6a9e837a7578d51da441f56bcbdb50c18804e/src/pytorch_ie/data/document.py#L253) method. For instance, in code below we add annotations to the doc by annotation name (_field_) but it is done one by one.

```python
   
  for doc in docs:
      for field in overwrite_annotations_with_predictions:
          for base_type, collection in doc.predictions.typed_collections:
              if field in collection:
                  doc.add_annotation(field, collection[field])

```

Maybe we need a `get` method to fetch all the annotations by their name.
Similarly, currently [add_annotation](https://github.com/ChristophAlt/pytorch-ie/blob/2eb6a9e837a7578d51da441f56bcbdb50c18804e/src/pytorch_ie/data/document.py#L247) or [add_prediction](https://github.com/ChristophAlt/pytorch-ie/blob/2eb6a9e837a7578d51da441f56bcbdb50c18804e/src/pytorch_ie/data/document.py#L250) methods add annotation one by one. Would it make sense if we can also add a list of annotations directly ?

**Comment by ArneBinder** [comment]
This is implemented.
