### ISSUE TITLE
Allow a dataset to be prepared from a dictionary instead of a collection of documents

### ISSUE THREAD

**Issue by ChristophAlt** [ChristophAlt/pytorch-ie#147]
The reason is that there may exist datasets that are so large they can't be iterated over in a reasonable time. For efficiency reasons we should allow the user to prepare a taskmodule by passing a dictionary prepare(dct) or prepare(**kwargs).

Solution: overload prepare of taskmodule to accept a dict / kwargs too.

**Comment by ArneBinder** [comment]
I don't think this is necessary, one can just provide the respective values directly to the taskmodule constructor and not call prepare at all.

**Comment by ArneBinder** [comment]
This is implemented via #248 when using `_post_prepare()`. Just pass the prepared attributes to the taskmodule as constructor agruments.
