### ISSUE TITLE
push_to_hub=True is broken

### ISSUE THREAD

**Issue by ArneBinder** [ChristophAlt/pytorch-ie#261]

**Comment by leonhardhennig** [comment]
Workaround for uploading a model:
Upgrade huggingface-hub dependency to >= 0.13.4
Follow instructions here:  https://huggingface.co/docs/huggingface_hub/guides/upload
```python
from huggingface_hub import HfApi
folder = "/path/to/model_save_dir"
repo_id = "orgname/repo"
hf_token = "your_hf_access_token"
api = HfApi()
api.upload_folder(folder_path=folder_path,
                      repo_id=repo_id,
                      repo_type="model",
                      token=hf_token)
```

**Comment by ArneBinder** [comment]
Some preparational steps:
1. login via `huggingface-cli login`: will ask for a token and give you the link to huggingface token management
2. install and setup git lfs (see https://git-lfs.github.com/):
	a. `curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash` and then
	b. `sudo apt update && sudo apt install git-lfs`
