### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by ChristophAlt** [ChristophAlt/pytorch-ie#78]
It's time for our first release. :partying_face: 

The most important parts are:
- [x] a bit more documentation (code comments, also see [simple_transformer_text_classification.py](https://github.com/ChristophAlt/pytorch-ie/blob/main/src/pytorch_ie/taskmodules/simple_transformer_text_classification.py), and ~sphinx documentation / readthedocs documentation~ enhance the readme)
- [x] working examples
- [x] a simple readme with getting started examples (PR: #96)
- [x] a working CI / CD pipeline that we can use to quickly publish releases to test.pypi, pypi and github, PR: #76
- [x] a few shields at the top of the readme
- [x] a pytorch-lightning-hydra template with a simple task (e.g. NER on conll03) that demonstrates the usage and can be copied with githubs template functionality (URL: https://github.com/ChristophAlt/pytorch-ie-hydra-template), see https://github.com/ChristophAlt/pytorch-ie-hydra-template/pull/1

As we're still at version 0.x and a lot of things are going to change, code coverage and perfect documentation for internal functionality won't be a priority.

**Comment by ArneBinder** [comment]
This is done.
